-- MySQL Script generated by MySQL Workbench
-- Tue Aug  9 23:36:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project_manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project_manager` ;

-- -----------------------------------------------------
-- Schema project_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_manager` DEFAULT CHARACTER SET utf8 ;
USE `project_manager` ;


-- -----------------------------------------------------
-- Table `project_manager`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_manager`.`projects` ;

CREATE TABLE IF NOT EXISTS `project_manager`.`projects` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `project_manager`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_manager`.`units` ;

CREATE TABLE IF NOT EXISTS `project_manager`.`units` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(48) NOT NULL,
  `state` TINYINT(1) UNSIGNED NOT NULL,
  `description` VARCHAR(4096) NOT NULL,
  `projectsID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_features_projects`
    FOREIGN KEY (`projectsID`)
    REFERENCES `project_manager`.`projects` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `project_manager`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_manager`.`images` ;

CREATE TABLE IF NOT EXISTS `project_manager`.`images` (
  `ID` INT NOT NULL,
  `source` VARCHAR(128) NOT NULL,
  `unitsID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_images_features1`
    FOREIGN KEY (`unitsID`)
    REFERENCES `project_manager`.`units` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `project_manager`.`parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_manager`.`parents` ;

CREATE TABLE IF NOT EXISTS `project_manager`.`parents` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_parents_features1`
    FOREIGN KEY (`ID`)
    REFERENCES `project_manager`.`units` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `project_manager`.`children`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_manager`.`children` ;

CREATE TABLE IF NOT EXISTS `project_manager`.`children` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_children_features1`
    FOREIGN KEY (`ID`)
    REFERENCES `project_manager`.`units` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `project_manager`.`subunits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_manager`.`subunits` ;

CREATE TABLE IF NOT EXISTS `project_manager`.`subunits` (
  `parentsID` INT NOT NULL,
  `childrenID` INT NOT NULL,
  PRIMARY KEY (`parentsID`, `childrenID`),
  CONSTRAINT `fk_subunits_parents1`
    FOREIGN KEY (`parentsID`)
    REFERENCES `project_manager`.`parents` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subunits_children1`
    FOREIGN KEY (`childrenID`)
    REFERENCES `project_manager`.`children` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





INSERT INTO `projects`(`name`) VALUES ("Plankton"), ("osu!routine");

INSERT INTO `units`(`state`, title, `description`, `projectsID`)
VALUES (0, "Color/Gradient picker", "HTML element for picking color or gradient for theme.", 1),
(0, "'new' element", "HTML element that displays the color/gradient that will be used as new color.", 1),
(0, "'slider' component", "Input element for inputing a value from range.", 1),
(2, "'tooltip' behaviour", "After certain amount of time desplays a message near user cursor.", 1),
(3, "Tooltip clipping outside of window", "When cursor is near right side, the tooltip gets clipped. Expected: Tooltip will stick to right side.", 1);
INSERT INTO `units`(`state`, `description`, `projectsID`, `title`)
VALUES (2, "Form to define how the training days will be structured.", 2, "Day structure form")

INSERT INTO `subunits`(`parentsID`, `childrenID`) VALUES (1,2), (1,3), (4,5);

INSERT INTO `parents`(`ID`) VALUES (1), (4);

INSERT INTO `children`(`ID`) VALUES (2), (3), (5);
